name: Build and Sign APK

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Change wrapper permissions
      run: chmod +x gradlew

    - name: Extract App Version Name
      id: get_version
      run: |
        VERSION_NAME=$(grep "versionName" app/build.gradle.kts | head -n 1 | awk -F'"' '{print $2}')
        if [ -z "$VERSION_NAME" ]; then
          VERSION_NAME=$(grep "versionName" app/build.gradle.kts | head -n 1 | awk -F"'" '{print $2}')
        fi
        echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT

    - name: Build Release APK
      run: |
        export ACOUSTID_KEY=$(printf "\x53\x41\x6f\x59\x4f\x65\x64\x38\x54\x65")
        ./gradlew assembleRelease

    - name: Sign Android APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0" 

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Signed-Release-APK
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v${{ steps.get_version.outputs.version }}"
        name: "Release v${{ steps.get_version.outputs.version }}"
        draft: false
        prerelease: false
        files: ${{ steps.sign_app.outputs.signedReleaseFile }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
